-- Seed lessons if table is empty
DO $$
BEGIN
  IF (SELECT COUNT(*) FROM public.lessons) < 5 THEN

    INSERT INTO public.lessons (module, category, level, title, xp_reward, content_json) VALUES

    ('ingles','vocabulario',1,'Cores em Inglês',20,'{"questions":[{"type":"choice","prompt":"Como se diz AZUL em inglês?","options":["Red","Blue","Green","Yellow"],"answer":1,"explanation":"Blue = Azul. Red = Vermelho, Green = Verde, Yellow = Amarelo."},{"type":"choice","prompt":"What color is the sun?","options":["Blue","Green","Yellow","White"],"answer":2,"explanation":"The sun is Yellow! O sol é amarelo."},{"type":"choice","prompt":"Como se diz VERMELHO?","options":["Pink","Orange","Red","Purple"],"answer":2,"explanation":"Red = Vermelho."},{"type":"match","prompt":"Combine as cores:","pairs":[{"left":"Blue","right":"Azul"},{"left":"Red","right":"Vermelho"},{"left":"Green","right":"Verde"},{"left":"Yellow","right":"Amarelo"}],"explanation":"Cores básicas em inglês!"},{"type":"choice","prompt":"Como se diz VERDE?","options":["Blue","Red","Green","Yellow"],"answer":2,"explanation":"Green = Verde."}]}'),

    ('ingles','vocabulario',1,'Números 1-10',20,'{"questions":[{"type":"choice","prompt":"Como se diz 5 em inglês?","options":["Four","Six","Five","Seven"],"answer":2,"explanation":"Five = 5."},{"type":"choice","prompt":"How much is TEN?","options":["8","9","10","11"],"answer":2,"explanation":"Ten = 10."},{"type":"choice","prompt":"Como se diz 3?","options":["One","Two","Three","Four"],"answer":2,"explanation":"Three = 3."},{"type":"match","prompt":"Combine os números:","pairs":[{"left":"One","right":"1"},{"left":"Three","right":"3"},{"left":"Seven","right":"7"},{"left":"Ten","right":"10"}],"explanation":"Números em inglês!"},{"type":"choice","prompt":"Quantos dedos em uma mão? (em inglês)","options":["Four","Five","Six","Seven"],"answer":1,"explanation":"Five fingers! Cinco dedos."}]}'),

    ('ingles','gramatica',1,'Verbo To Be',25,'{"questions":[{"type":"choice","prompt":"I _____ a student.","options":["is","are","am","be"],"answer":2,"explanation":"Com I usamos AM: I am a student."},{"type":"choice","prompt":"She _____ beautiful.","options":["am","are","is","be"],"answer":2,"explanation":"Com She usamos IS."},{"type":"choice","prompt":"They _____ friends.","options":["is","am","are","be"],"answer":2,"explanation":"Com They usamos ARE."},{"type":"choice","prompt":"We _____ happy.","options":["is","am","are","be"],"answer":2,"explanation":"Com We usamos ARE."},{"type":"match","prompt":"Combine o pronome com o verbo:","pairs":[{"left":"I","right":"am"},{"left":"She","right":"is"},{"left":"They","right":"are"},{"left":"We","right":"are"}],"explanation":"Verbo To Be no presente!"}]}'),

    ('ingles','vocabulario',1,'Saudações',20,'{"questions":[{"type":"choice","prompt":"Como se diz BOM DIA?","options":["Good night","Good afternoon","Good morning","Good evening"],"answer":2,"explanation":"Good morning = Bom dia!"},{"type":"choice","prompt":"Como se despedir?","options":["Hello","Hi","Goodbye","Please"],"answer":2,"explanation":"Goodbye = Tchau/Adeus."},{"type":"choice","prompt":"MEU NOME É em inglês?","options":["I have name","My name is","I am name","Name me"],"answer":1,"explanation":"My name is... = Meu nome é..."},{"type":"match","prompt":"Combine as saudações:","pairs":[{"left":"Good morning","right":"Bom dia"},{"left":"Thank you","right":"Obrigado"},{"left":"Please","right":"Por favor"},{"left":"Sorry","right":"Desculpe"}],"explanation":"Saudações básicas!"},{"type":"choice","prompt":"Como dizer OBRIGADO?","options":["Please","Sorry","Thank you","Excuse me"],"answer":2,"explanation":"Thank you = Obrigado!"}]}'),

    ('ingles','gramatica',2,'Simple Past',30,'{"questions":[{"type":"choice","prompt":"She _____ TV yesterday.","options":["watch","watchs","watched","watching"],"answer":2,"explanation":"No Simple Past verbos regulares recebem -ED."},{"type":"choice","prompt":"They _____ to the park on Sunday.","options":["walk","walked","walking","walks"],"answer":1,"explanation":"Walk → Walked no Simple Past."},{"type":"choice","prompt":"Qual palavra indica passado?","options":["Tomorrow","Now","Yesterday","Always"],"answer":2,"explanation":"Yesterday = ontem, indica Simple Past."},{"type":"match","prompt":"Conjugue no passado:","pairs":[{"left":"play","right":"played"},{"left":"work","right":"worked"},{"left":"study","right":"studied"},{"left":"stop","right":"stopped"}],"explanation":"Verbos regulares no Simple Past!"},{"type":"choice","prompt":"I _____ English last night. (study)","options":["study","studyed","studied","studying"],"answer":2,"explanation":"study → studied (Y vira IED)."}]}'),

    ('ingles','gramatica',3,'Present Perfect',40,'{"questions":[{"type":"choice","prompt":"I _____ to Japan. (experiência)","options":["went","have been","was","go"],"answer":1,"explanation":"Present Perfect para experiências de vida sem tempo definido."},{"type":"choice","prompt":"She _____ the report yesterday.","options":["has finished","finished","have finished","finish"],"answer":1,"explanation":"Com Yesterday (tempo definido) usamos Simple Past."},{"type":"choice","prompt":"Qual frase está CORRETA?","options":["I have seen him yesterday.","I saw him yesterday.","I have saw him.","I seen him."],"answer":1,"explanation":"Com Yesterday usamos Simple Past: I saw him yesterday."},{"type":"match","prompt":"Relacione:","pairs":[{"left":"Experiência de vida","right":"Present Perfect"},{"left":"Ação com tempo definido","right":"Simple Past"},{"left":"Ação recém concluída","right":"Present Perfect"},{"left":"Ação concluída ontem","right":"Simple Past"}],"explanation":"Present Perfect vs Simple Past!"},{"type":"choice","prompt":"I have never _____ sushi.","options":["eat","ate","eaten","eating"],"answer":2,"explanation":"Have + never + past participle: eaten."}]}'),

    ('matematica','basica',1,'Adição e Subtração',20,'{"questions":[{"type":"choice","prompt":"Quanto é 25 + 37?","options":["52","62","61","72"],"answer":1,"explanation":"25+37: 5+7=12, escreve 2 carrega 1; 2+3+1=6. Total: 62."},{"type":"choice","prompt":"100 - 43 = ?","options":["57","67","47","53"],"answer":0,"explanation":"100 - 43 = 57. Confirme: 43+57=100 ✓"},{"type":"choice","prompt":"150 produtos, vendeu 68. Quantos restaram?","options":["72","82","92","62"],"answer":1,"explanation":"150 - 68 = 82 produtos."},{"type":"choice","prompt":"999 + 1 = ?","options":["999","1000","1001","998"],"answer":1,"explanation":"999 + 1 = 1.000. Passamos de centena para milhar!"},{"type":"choice","prompt":"João tem 45 reais e ganhou 28. Total?","options":["63","73","83","53"],"answer":1,"explanation":"45 + 28 = 73 reais."}]}'),

    ('matematica','basica',1,'Multiplicação e Divisão',20,'{"questions":[{"type":"choice","prompt":"7 × 8 = ?","options":["54","56","58","64"],"answer":1,"explanation":"7×8 = 56. Dica: 7×8=7×4×2=28×2=56."},{"type":"choice","prompt":"72 ÷ 9 = ?","options":["6","7","8","9"],"answer":2,"explanation":"72÷9=8, pois 9×8=72."},{"type":"choice","prompt":"12 ovos × 5 caixas = ?","options":["50","55","60","65"],"answer":2,"explanation":"12×5=60 ovos."},{"type":"choice","prompt":"48 balas ÷ 6 crianças = ?","options":["6","7","8","9"],"answer":2,"explanation":"48÷6=8 balas cada."},{"type":"choice","prompt":"15 × 4 = ?","options":["45","55","60","65"],"answer":2,"explanation":"15×4=60. Dica: 10×4+5×4=40+20=60."}]}'),

    ('matematica','porcentagem',1,'Porcentagem Básica',25,'{"questions":[{"type":"choice","prompt":"10% de 200 = ?","options":["10","20","200","2"],"answer":1,"explanation":"10% = dividir por 10. 200÷10=20."},{"type":"choice","prompt":"50% de 80 = ?","options":["20","30","40","50"],"answer":2,"explanation":"50% = metade. 80÷2=40."},{"type":"choice","prompt":"R$100 com 20% desconto = ?","options":["R$80","R$70","R$85","R$90"],"answer":0,"explanation":"20% de 100=20. 100-20=R$80."},{"type":"choice","prompt":"25% equivale a qual fração?","options":["1/3","1/5","1/4","1/2"],"answer":2,"explanation":"25%=25/100=1/4."},{"type":"choice","prompt":"Salário R$2000 + 15% de aumento = ?","options":["R$2100","R$2200","R$2300","R$2400"],"answer":2,"explanation":"15% de 2000=300. 2000+300=R$2300."}]}'),

    ('matematica','algebra',2,'Equações 1° Grau',30,'{"questions":[{"type":"choice","prompt":"2x + 4 = 10. Qual o valor de x?","options":["2","3","4","5"],"answer":1,"explanation":"2x=10-4=6. x=6÷2=3."},{"type":"choice","prompt":"x - 7 = 13. x = ?","options":["6","13","20","26"],"answer":2,"explanation":"x=13+7=20."},{"type":"choice","prompt":"3x = 21. x = ?","options":["6","7","8","9"],"answer":1,"explanation":"x=21÷3=7."},{"type":"choice","prompt":"Daqui a 5 anos terá 30 anos. Qual a equação?","options":["x-5=30","x+5=30","5x=30","x×30=5"],"answer":1,"explanation":"Idade atual + 5 = 30. x+5=30, x=25."},{"type":"choice","prompt":"4x - 8 = 16. x = ?","options":["4","5","6","7"],"answer":2,"explanation":"4x=16+8=24. x=24÷4=6."}]}'),

    ('matematica','geometria',2,'Área e Perímetro',30,'{"questions":[{"type":"choice","prompt":"Área do retângulo: base 8m, altura 5m?","options":["13m²","26m²","40m²","80m²"],"answer":2,"explanation":"Área=base×altura=8×5=40m²."},{"type":"choice","prompt":"Perímetro do quadrado lado 6cm?","options":["12cm","18cm","24cm","36cm"],"answer":2,"explanation":"Perímetro=4×lado=4×6=24cm."},{"type":"choice","prompt":"Fórmula da área do triângulo?","options":["b×h","(b×h)÷2","b+h","2×(b+h)"],"answer":1,"explanation":"Área triângulo=(base×altura)÷2."},{"type":"choice","prompt":"Quarto 4m×3m. Área para piso?","options":["7m²","12m²","14m²","24m²"],"answer":1,"explanation":"Área=4×3=12m²."},{"type":"choice","prompt":"Triângulo base 10m altura 6m. Área?","options":["30m²","40m²","50m²","60m²"],"answer":0,"explanation":"Área=(10×6)÷2=60÷2=30m²."}]}'),

    ('matematica','algebra',3,'Equações 2° Grau',40,'{"questions":[{"type":"choice","prompt":"x² - 5x + 6 = 0. Quais são as raízes?","options":["x=1 e x=6","x=2 e x=3","x=-2 e x=-3","x=1 e x=-6"],"answer":1,"explanation":"Fatorando: (x-2)(x-3)=0 → x=2 ou x=3."},{"type":"choice","prompt":"Se Δ < 0, a equação tem:","options":["Duas raízes reais","Uma raiz real","Nenhuma raiz real","Infinitas raízes"],"answer":2,"explanation":"Δ<0 significa sem raízes reais."},{"type":"choice","prompt":"Qual o Δ para x² - 6x + 9 = 0?","options":["0","9","36","-9"],"answer":0,"explanation":"Δ=(-6)²-4×1×9=36-36=0. Raiz dupla!"},{"type":"choice","prompt":"2x² + 4x = 0. Uma raiz é x=0. Qual a outra?","options":["1","-1","2","-2"],"answer":3,"explanation":"2x(x+2)=0 → x=0 ou x=-2."},{"type":"choice","prompt":"Δ=25, a=1, b=-7. Raiz maior?","options":["4","5","6","7"],"answer":2,"explanation":"x=(-(-7)+√25)/(2×1)=(7+5)/2=12/2=6."}]}');

  END IF;
END $$;
